sudo: false
language: php

branches:
  only:
      - master

env:
  global:
    - CHECK_CODE_STYLE="no"
    - COMPOSER_FLAGS=""
    - COMPOSER_MEMORY_LIMIT=-1
    - ENABLE_CODE_COVERAGE="no"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - SYMFONY_VERSION=""

matrix:
    fast_finish: true
    include:

      # no flag build with code coverage:
      - php: 7.4
        env: ENABLE_CODE_COVERAGE="yes"

      - php: 7.3
        env:
          - SYMFONY_VERSION="^4.4"
          - COMPOSER_FLAGS="--prefer-lowest"
          - SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT=1

      # most recent versions:
      - php: 7.4
        env:
          - CHECK_CODE_STYLE="yes"

      - php: 8.0snapshot
        env: SYMFONY_VERSION="^5.2"

      # bleeding edge (unreleased dev versions where failures are allowed):
      - php: nightly # PHP 8.1
        env: SYMFONY_VERSION="^5.3"

    allow_failures:
      - env: SYMFONY_VERSION="^5.3"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/symfony-bridge/.phpunit

before_install:
  - if [[ "$ENABLE_CODE_COVERAGE" != "yes" ]]; then phpenv config-rm xdebug.ini || true; fi;
  - if [[ "$SYMFONY_VERSION" != "" ]]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [[ "$CHECK_CODE_STYLE" != "yes" ]]; then composer remove "friendsofphp/php-cs-fixer" --no-update --no-interaction --dev; fi;

install:
  - |
    # Set composer's platform to php 7.4 if we're on php 8 and require "phpspec/prophecy"
    # (as native support for prophecy was removed from PHPUnit 9)
    echo $TRAVIS_PHP_VERSION
    if php -r "exit (PHP_MAJOR_VERSION == 8 ? 0 : 1);"; then
      echo "Set composer's platform to php 7.4"
      composer config platform.php 7.4.99
      composer require "phpspec/prophecy-phpunit:^2.0" --no-update --no-interaction --dev
    fi
  - composer update --prefer-dist --no-interaction --optimize-autoloader --prefer-stable --no-progress $COMPOSER_FLAGS
  - if [[ "$ENABLE_CODE_COVERAGE" == "yes" ]]; then composer require --dev satooshi/php-coveralls; fi;

script:
  - if [[ "$ENABLE_CODE_COVERAGE" == "yes" ]]; then vendor/bin/simple-phpunit --coverage-text --coverage-clover build/logs/clover.xml; else vendor/bin/simple-phpunit; fi;
  - if [[ "$CHECK_CODE_STYLE" == "yes" ]]; then PHP_CS_FIXER_FUTURE_MODE=1 vendor/bin/php-cs-fixer fix --config=.php_cs --dry-run --no-interaction --diff; fi;

after_success:
  - if [[ "$ENABLE_CODE_COVERAGE" == "yes" ]]; then php vendor/bin/coveralls -v; fi;
