build: false
platform: x86
clone_folder: c:\projects\elao\php-enums

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst -y php composer
  - refreshenv
  - cd c:\tools\php74
  - copy php.ini-production php.ini /Y
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_pdo_sqlite.dll >> php.ini
  - echo memory_limit=-1 >> php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  - composer install --no-progress --no-interaction

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - vendor\bin\simple-phpunit.bat
