build: false
platform: x86
clone_folder: c:\projects\elao\php-enums

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst -y php composer
  - refreshenv
  - cd c:\tools\php80
  - copy php.ini-production php.ini /Y
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_pdo_sqlite.dll >> php.ini
  - echo memory_limit=-1 >> php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  # Until PHP 8 full support by third-parties:
  - composer config platform.php 7.4.99
  # Require "phpspec/prophecy" for PHPUnit 9 used with PHP 8:
  - composer require phpspec/prophecy-phpunit:^2.0 --no-update --no-interaction --dev
  - composer update --prefer-dist --no-interaction --optimize-autoloader --prefer-stable --no-progress

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - vendor\bin\simple-phpunit.bat
